function [new_zc_cell] = AN_and_Onset_Reconstruct_AssignData_eachChannel(Onset_data_file)

% This function converts the spike trains from accroding to sensitivity
% level to channel,
% For 'Onset' type data generated by Leslie's Leaky integrated fire neurone. 

% The data should be loaded from the file
big.data = load(Onset_data_file);

% Pick out some useful information
% How many channels?
num_channels    = big(1).data.ANparams.channels;
% How many sen levels?
num_sen_levels  = big(1).data.ANparams.iterations;


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% % This one is constructing a huge big cell array to store all the data.
% zc_cell = cell(num_sen_levels,num_channels);
% h = waitbar(0,'Please wait. First cell array is being created ...');
% for i = 1:num_sen_levels
%     for ch = 1:num_channels
%         zc_cell{i,ch}=AN_FindData(an_data_files,i,ch);
%     end
%     waitbar(i /num_sen_levels)
% end
% close(h)

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% This is for taking all the data from that big cell array and assigning them according to the number of channels 
new_zc_cell = cell(1,num_channels);
log = false;
h2 = waitbar(0,'Please wait. Second cell array is being created ...');
for ch = 1:num_channels
    final_Time_Value = 0;
    for i = 1:num_sen_levels
        
        Time_Value = AN_and_Onset_FindData(Onset_data_file,(num_sen_levels-i+1),ch);
        %zc_cell{i,ch}=AN_FindData(an_data_files,i,ch);
        %Time_Value = zc_cell{(num_sen_levels-i+1),ch};
        Time_Value(Time_Value==0)=[];
        if (isempty(Time_Value))
            log = true;
            Copy_Time_Value = 0;
        else
            if i==1
                % Do nothing.
%                 if (isempty(Time_Value))
%                     Copy_Time_Value = 0;
%                 end
            else
%                 disp(ch)
%                 disp(i)
                Time_Value = setdiff(Time_Value,Copy_Time_Value);
                
            end
            levels = zeros(length(Time_Value),1);
            for j = 1:length(Time_Value)
                levels(j,1) = (num_sen_levels-i+1);
            end
            if (isempty(Time_Value))
                new_Time_Value = [];
            else
                new_Time_Value = cat(2,Time_Value,levels);
            end
            if i==1
                final_Time_Value = new_Time_Value;
            elseif log
                final_Time_Value = new_Time_Value;
                log = false;
            else
                final_Time_Value = cat(1,final_Time_Value,new_Time_Value);
            end
            % It is necessary to copy the data inside Time_Value at this
            % instance , so that it can be compared to the next Time_Value.
            if (isempty(final_Time_Value))
                
            else
                Copy_Time_Value = final_Time_Value(:,1);
            end
        end
    
    end
    if size(final_Time_Value) ~= 0
        final_Time_Value = sortrows(final_Time_Value,1);
    end
    new_zc_cell{1,ch} = final_Time_Value;
    waitbar(ch/num_channels)
end
close(h2)




end
